experimentalTernaries: true
printWidth: 80
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always
requirePragma: false
insertPragma: false
proseWrap: preserve
htmlWhitespaceSensitivity: css
endOfLine: lf
embeddedLanguageFormatting: off
singleAttributePerLine: true
