import _import, { rules } from 'eslint-plugin-import';
import typescriptEslint from '@typescript-eslint/eslint-plugin';
import { fixupPluginRules } from '@eslint/compat';
import globals from 'globals';
import tsParser from '@typescript-eslint/parser';

const baseRules = {
    "for-direction": 2,
    "getter-return": [
      2,
      { "allowImplicit": false }
    ],
    "no-await-in-loop": 0,
    "no-compare-neg-zero": 2,
    "no-cond-assign": [2, "always"],
    "no-console": 0,
    "no-constant-condition": 2,
    "no-debugger": 2,
    "no-dupe-keys": 2,
    "no-empty": 2,
    "no-empty-character-class": 2,
    "no-ex-assign": 2,
    "no-invalid-regexp": 2,
    "no-irregular-whitespace": 2,
    "no-sparse-arrays": 2,
    "no-template-curly-in-string": 2,
    "no-unexpected-multiline": 2,
    "no-unreachable": 2,
    "no-unsafe-finally": 2,
    "no-unsafe-negation": 2,
    "use-isnan": 2,
    "valid-typeof": 2,
    "accessor-pairs": 2,
    "array-callback-return": 2,
    "block-scoped-var": 2,
    "complexity": 0,
    "curly": 2,
    "default-case": 2,
    "dot-location": [2, "property"],
    "dot-notation": 2,
    "eqeqeq": 2,
    "guard-for-in": 2,
    "no-alert": 2,
    "no-caller": 2,
    "no-case-declarations": 2,
    "no-div-regex": 2,
    "no-else-return": 2,
    "no-empty-function": 2,
    "no-empty-pattern": 2,
    "no-eq-null": 2,
    "no-eval": 2,
    "no-extend-native": 2,
    "no-extra-bind": 2,
    "no-extra-label": 2,
    "no-fallthrough": 2,
    "no-floating-decimal": 2,
    "no-global-assign": 2,
    "no-implicit-coercion": [2, { "allow": ["!!"] }],
    "no-implicit-globals": 2,
    "no-implied-eval": 2,
    "no-iterator": 2,
    "no-labels": 2,
    "no-lone-blocks": 2,
    "no-loop-func": 2,
    "no-multi-str": 2,
    "no-new": 2,
    "no-new-func": 2,
    "no-new-wrappers": 2,
    "no-octal": 2,
    "no-octal-escape": 2,
    "no-param-reassign": 2,
    "no-proto": 2,
    "no-redeclare": [2, { "builtinGlobals": true }],
    "no-restricted-properties": 2,
    "no-return-assign": [2, "except-parens"],
    "no-return-await": 2,
    "no-script-url": 2,
    "no-self-assign": [2, { "props": true }],
    "no-self-compare": 2,
    "no-sequences": 2,
    "no-throw-literal": 2,
    "no-unmodified-loop-condition": 2,
    "no-unused-labels": 2,
    "no-useless-call": 2,
    "no-useless-concat": 2,
    "no-useless-return": 2,
    "no-with": 2,
    "prefer-promise-reject-errors": 2,
    "radix": 2,
    "require-await": 2,
    "vars-on-top": 2,
    "wrap-iife": 2,
    "yoda": 2,
    "strict": 2,
    "init-declarations": 2,
    "no-catch-shadow": 2,
    "no-delete-var": 2,
    "no-label-var": 2,
    "no-restricted-globals": [2, "event"],
    "no-shadow-restricted-names": 2,
    "no-undef": 2,
    "no-undef-init": 2,
    "no-undefined": 2,
    "no-unused-vars": 0,
    "no-use-before-define": 0,
    "callback-return": 0,
    "global-require": 2,
    "handle-callback-err": [2, "error"],
    "no-buffer-constructor": 2,
    "no-mixed-requires": 2,
    "no-new-require": 2,
    "no-path-concat": 2,
    "no-process-exit": 2,
    "no-restricted-modules": 2,
    "no-sync": 0
  }


export default [
    {
        files: ['src/**/*.ts'],
        plugins: {
            import: fixupPluginRules(_import),
            '@typescript-eslint': typescriptEslint,
        },

        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.node,
                __ENV__: false,
                __DEV__: false,
                __STAGE__: false,
                __PROD__: false,
                __TEST__: false,
                __MODEL__: false,
                __: false,
                shallow: false,
                mount: false,
            },

            parser: tsParser,
            ecmaVersion: 2023,
            sourceType: 'module',

            parserOptions: {
                ecmaFeatures: {
                    impliedStrict: true,
                    legacyDecorators: true,
                },
            },
        },

        rules: baseRules,
    },
    {
        files: ['tests/**/*.ts'],
        plugins: {
            "import": fixupPluginRules(_import),
            "@typescript-eslint": typescriptEslint,
        },
        languageOptions: {
            globals: {
                ...globals.node,
                ...globals.jest,
                describe: false,
                test: false,
                it: false,
            },
            parser: tsParser,
            ecmaVersion: 2023,
            sourceType: 'module',
            parserOptions: {
                ecmaFeatures: {
                    impliedStrict: true,
                    legacyDecorators: true,
                },
            },
        },

        rules: {...baseRules, 'no-undef': 'off',}
    }
];
